# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_carro', models.PositiveIntegerField(verbose_name='Número carro')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name_plural': 'Carros',
                'verbose_name': 'Carro',
                'ordering': ['num_carro'],
            },
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_linha', models.CharField(max_length=10, verbose_name='Linha do veiculo')),
                ('nome_linha', models.CharField(max_length=100, verbose_name='Nome da linha')),
            ],
            options={
                'verbose_name_plural': 'Linhas',
                'verbose_name': 'Linha',
                'ordering': ['num_linha'],
            },
        ),
    ]
