# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAtual', models.DateField(verbose_name='Data Atual')),
                ('horario_entrada', models.TimeField(verbose_name='Horario de Entrada')),
                ('horario_saida', models.TimeField(verbose_name='Horario de Saida')),
                ('folga', models.BooleanField(default=False, verbose_name='Folga')),
                ('total_horas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carro', to='rota.Carro')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Linha', to='rota.Linha')),
            ],
            options={
                'verbose_name_plural': 'Periodos',
                'verbose_name': 'Periodo',
                'ordering': ['dataAtual'],
            },
        ),
    ]
